#!/usr/bin/ruby
puts `find ./ -name *.as -o -name *.mxml | xargs svn propdel license`
puts `find ./ -name *.as -o -name *.mxml | xargs svn propset copyright -F COPYRIGHT`
puts `find ./ -name *.as -o -name *.mxml | xargs svn propset source -F SOURCE`